### ISSUE TITLE
gold?

### ISSUE THREAD

**Issue by ddbgamer** [DakotaPride/create-back-to-the-kitchen#1]
![2024-03-16_17 58 54](https://github.com/DakotaPride/create-back-to-the-kitchen/assets/163671687/cc1d2a2a-b299-489f-ab42-2f55d84e7185)
was just mining when I suddenly found a lot of gold. I wouldn't be surprised if it is a feature in a mod but I don't know what mod so just to be sure I reported it. (and if it's an feature it is maybe a bot OP)

**Comment by DakotaPride** [comment]
It should be fixed now, but might not be noticeable in already-generated chunks!
